import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import '../presentation/screen/recipe_detail_screen.dart';


class RecipeModel {
  final String name;
  final String image;
  final String category;
  final String duration;
  final String serving;
  final List<String> ingredients;
  final List<String> instructions;

  RecipeModel({
    required this.name,
    required this.image,
    required this.category,
    required this.duration,
    required this.serving,
    required this.ingredients,
    required this.instructions,
  });
}

final trandingRecipes = [
  RecipeModel(
    name: "Shrimp Sushi Bowls",
    image: "assets/shrimp_sushi_bowls.jpeg",
    category: "Seafood",
    duration: "1 Hour",
    serving: "2 Servings",
    ingredients:  [
      '1 cangkir nasi sushi',
      '2 gelas air',
      '1/4 cangkir cuka beras',
      '1 sdm gula',
      '1/2 sdt garam',
      '1 pon udang, dimasak dan dikupas',
      '1 buah alpukat, iris',
      '1 mentimun, diiris',
      '1 wortel, diparut',
      '1/2 cangkir edamame',
      '1 sdm biji wijen',
      'Kecap asin, secukupnya',
    ],
    instructions: [
      'Basuh nasi sushi dengan air dingin sampai airnya jernih.',
      'Campurkan beras dan air dalam panci dan didihkan. Kecilkan api menjadi rendah, tutup, dan biarkan mendidih selama 20 menit.',
      'Dalam mangkuk kecil, campur cuka beras, gula pasir, dan garam hingga larut. Tuangkan di atas nasi dan aduk rata.',
      'Bagi nasi menjadi dua mangkuk.',
      'Tata udang, alpukat, mentimun, wortel, dan edamame di atas nasi.',
      'Taburkan dengan biji wijen.',
      'Sajikan dengan kecap di sampingnya.',
    ],
  ),

  RecipeModel(
    name: "Crispy Honey Ginger Salmon Bowl",
    image: "assets/crispy_honey_ginger_salmon_bowl.png",
    category: "Seafood",
    duration: "1 Hour",
    serving: "3 Seving",
    ingredients: [
  'Untuk Salmon :',
      '4 fillet salmon (dengan kulit atau tanpa kulit)',
      '1 sendok makan minyak zaitun',
      'Garam dan merica secukupnya''Untuk Saus Madu Jahe:',
      '1/4 cangkir madu',
      '2 sendok makan kecap asin',
      '1 sendok makan jahe segar,parut',
      '2 siung bawang putih, cincng halus',
      '1 sendok makan cuka beras',
      '1 sendok teh minyak wijen',
      '1 sendok teh tepung maizena dicampur dengan 1 sendok makan air',
      'Untuk Bowl:',
      '2 cangkir nasi matang (putih,coklat,atau jasmine)',
      '1 mentimun, diiris tipis',
      '1 alpukat, diiris',
      '1 wortel, diparut',
      '1/4 cangkir edamame, dimasak',
      '2 sendok makan biji wijen',
      '2 batang daun bawang, diirs',
      'Daun ketumbar segar untuk hiasan',
      'Irisan jeruk nipis untuk disajikan',
    ],
    instructions: [
      'Siapkan Saus:',
    'Dalam panci kecil, campurkan madu, kecap asin,jahe,bawang putih,cuka beras,dan minyak wijen',
    'Didihkan campuran tersebut dengan api sedang, sambil sesakli diaduk',
    'Jika anda ingin saus lebih kental, tambahkan campuran maizena dan air, lalu didihkan kembali sampai saus mengental',
    'angkat dari api dan sisihkan',
    'Masak Salmon:',
    'Bumbu fillet salmon dengn garam dan merica',
    'Panaskan minyak zaitun dalam wajan besar diatas api sedang-tinggi',
    'Tambahkan fillet salmon, dengan kulit menghadap ke bawah jika menggunakan fillet dengan kulit',
    'Masak selama 4-5 menit, atau sampai kulitnya renyah dan salmon setengah matang',
    'Balik filet salmon dengan hati-hati dan masak lagi selama 3-4 menit, atau sampai salmon matang sesuai selera anda',
    'Angkat salmon dari wajan dan olesi dengan saus madu jahe secara merata',
    'Susun Bowl:',
    'Bagi nasi matang ke dalam empat mangkuk',
    'Letakkan satu fillet salmon di setiap mangkuk',
    'Susun irisan mentimun, alpukat, wortel, dan edamame disekitar salmon',
    'Taburi dengan biji wijen dan irisan daun bawang',
    'Hias dengan daun ketumbar segar dan sajikan dengan irisan jeruk nipis di samping',

  ],
  ),
  RecipeModel(
    name: "Grilled Thai Red Curry Shrimp",
    image: "assets/grilled_thai_red_curry_shrimp.jpeg",
    category: "Seafood",
    duration: "1 Hour",
    serving: "2 Seving", ingredients: [
      'Untuk Udang:',
    ' 500 gram udang besar, kupas dan bersihkan, sisakan ekornya',
    '2 sendok makan minyak kelapa atau minyak sayur',
    '2 sendok makan pasta kari merah Thailand',
    '2 sendok makan kecap ikan',
    '1 sendok makan air jeruk nipis',
    '2 sendok makan santan kental',
    '1 sendok teh gula kelapa atau gulapasir',
    '2 siung bawang putih, cincang halus',
    '1 sendok teh jahe parut',
    'Tusuk sate bambu, rendam dalam air selama 30 menit',
    'Untuk Saus Pendamping:',
    '1/4 cangkir santan kental',
    '1 sendok teh pasta kari merah Thailand',
    '1 sendok teh kecap ikan',
    '1 sendok makan air jeruk nipis',
    ' 1 sendok teh gula kelapa atau gula pasir',
    'Untuk Penyajian:',
    'Daun ketumbar segar, cincang kasar',
    'Iris jeruk nipis',
    'Nasi putih  atau nasi ketan (opsional)',
  ], instructions: [
    'Dalam mangkuk besar, campurkan minyak kelapa, pasta kari merah, ',
    'kecap ikan, air jeruk nipis, santan, gula kelapa, bawang putih, dan jahe.',
    'Masukkan udang ke dalam campuran marinasi dan aduk hingga semua',
    'udang terbalut bumbu dengan rata.',
    'Tutup mangkuk dan simpan dalam kulkas selama 30 menit hingga 1 jam.',
    'Siapkan Saus Pendamping:',
    'Dalam mangkuk kecil, campurkan santan, pasta kari merah, kecap ikan,',
    'air jeruk nipis, dan gula kelapa.',
    'Aduk rata hingga semua bahan tercampur dengan baik. Sisihkan.',
    'Panggang Udang:',
    'Panaskan panggangan atau grill pan dengan api sedang-tinggi.',
    'Tusuk udang yang sudah dimarinasi pada tusuk satu bambu yang telah',
    'direndam.',
    'Panggang udang selama 2-3 menit per sisi atau hingga udang berubah',
    'warna mending merah muda dan matang dengan sempurna.',
    'Angkat udang dari panggung.',
    'Penyajian:',
    'Letakkan udang panggang di piring saji.',
    'Taburi dengan daun ketumbar segar yang sudah dicincang.',
    'Sajikan dengan irisan jeruk nipis di sampingnya.',
    'Sajikan udang panggang dengan saus pendamping dan nasi putih atau',
    'nasi ketan jika diinginkan.',
  ],
  ),
];

final latestRecipes = [
  RecipeModel(
    name: "Muschel-Spaghetti in Tomatensugo",
    image: "assets/muschel_spaghetti_in_tomatensugo.jpeg",
    category: "Pasta",
    duration: "1 Hour",
    serving: "2 Seving", ingredients: [
      'Bahan:',
      '400 gram spaghetti',
      '1 kg kerang (misalnya,kerang hitam),bersihkan dan buang yang terbuka',
      '4 sendok makan minyak zaitun',
      '4 siung bawang putih, cicang halus',
      '1 bawang bombay kecil, cincang halus',
      '800 gram tomat kaleng (dihancurkan atau cincang)',
      '1/2 cangkri anggur putih kering',
      '1 sendok teh cabai merah kering hancurkan (opsional)',
      'Garam dan lada hitam secukupnya',
      '1/4 cangkir daun peterseli segar, cincang halus',
      '1 sendok teh gula (opsional, untuk mengurangi keasaman tomat)',
      'Parmesan parut, untuk penyajian (opsional)',
      'Roti baguette atau roti panggang, untuk penyajian (opsional)',


  ], instructions: [
    'Petunjuk:',
    'Persiapan Kerang:',
    'Bersihkan kerang dengan menyikatnya dibawah air dingin yang mengalir dan',
    'buang kerang yang sudah terbuka dan tidak menutup saat diketuk.',
    'Saus Tomat:',
    'Panaskan 2 sendok makan minyak zaitun dalam wajan besar dengan api sedang.',
    'Tambahkan bawang putih dan bawang bombay, tumis hingga harum dan bawang bombay',
    'menjadi lunak, sekitar 5 menit.',
    'Tambahkan cabai merah kering jika menggunakan, dan aduk sebentar.',
    'Tuang tomat kaleng dan anggur putih ke dalamm wajan. Didihkan, lalu kecilkan',
    'api dan biarkan saus mendidih perlahan selama sekitar 20 menit. Tambahkan gula',
    'jika menggunakan untuk mengurangi keasaman tomat.',
    'Bumbui saus dengan garam dan lada hitam secukupnya.',
    'Memasak Spaghetti dan Kerang:',
    'Sambil menunggu saus tomat mendidih,masak spaghetti sesuai petunjuk pada',
    'kemasan hingga al dente.Tiriskan dan sisihkan.',
    'Panaskan sisa 2 sendok makan minyak zaitun dalam wajan besar lainnya dengan',
    'api sedang-tinggi.',
    'Tambahkan kerang yang sudag dibersihkan dan masak selama sekitar 3-4 menit,',
    'atau hingga kerang mulai terbuka. Buang kerang yang tidak terbuka.',
    'Tuang saus tomat ke dalam wajan dengan keranf, aduk rata, dan masak selama',
    '2-3 menit lagi agar semua rasa tercampur.',
    'Penyajian:',
    'Tambahkan spaghetti yang sudah dimasak kedalam wajan dengan kerang dan saus',
    'tomat. Aduk rata hingga spaghetti terbalut saus.',
    'Taburi dengan daun peterseli segar cincang.',
    'Sajikan segera dengan premesan parut diatasnya jika diinginkan, dan roti',
    'baguette atau roti panggang di sampingnya.',
  ],
  ),
  RecipeModel(
    name: "Beef Bibimbap with Triple Egg",
    image: "assets/beef_bibimbap_recipe.jpeg",
    category: "Beef",
    duration: "1 Hour",
    serving: "3 Seving", ingredients: [
      'Untuk Daging Sapi:',
    '300 gram daging sapi, iris tipis',
    '2 sendok makan kecap asin',
    '1 sendok makan minyak wijen',
    '1 sendok makan gula pasir',
    '2 siung bawang putih, cincang halus',
    '1 sendok teh jahe parut',
    'Untuk Sayuran dan Pelengkap:',
    '1 cangkir bayam, blansir',
    '1 cangkir tauge, blansir',
    '1 wortel, iris tipis panjang',
    '1 mentimun, iris tipis panjang',
    '1 cangkir jamur shiitake, iris tipis dan tumis',
    '1/2 cangkir kimchi',
    '4 porsi nasi putih matang',
    'Untuk Telur:',
    '2 telur ayam',
    '2 telur puyuh',
    '2 telur ikan (misalnya tobiko atau ikura)',
    'Untuk Saus Gochujang:',
    '3 sendok makan pasta gochujang',
    '1 sendok makan minyak wijen',
    '1 sendok makan air,'
        '1 sendok makan gula pasir',
    '1 sendok teh cuka beras',
  ], instructions:  [
    'Siapkan Daging Sapi:',
    'Dalam mangkuk, campurkan kecap asin, minyak wijen, gula pasir,',
    'bawang putih cincang, dan jahe parut.',
    'Masukkan iris daging sapi ke dalam campuran marinasi, aduk rata, dan',
    'diamkan selama 30 menit.',
    'Panaskan wajan dengan api sedang-tinggi dan tumis daging sapi hingga',
    'matang dan sedikit kecoklatan. Angkatan dan sisihkan',
   'Siapkan Saus Gochujang:',
'Dalam mangkuk kecil, campurkan pasta gochujang, minyak wijen, air, gula pasir,',
    'dan cuka beras.',
    'Aduk hingga semua bahan tercampur dengan baik. Sisihkan.',
    'Masak Teur:'
        'Panskan sedikit minyak dalam wjan kecil di atas api sedang.',
    ' Pecahkan telur ayam satu per satu ke dalam wajan dan masak hingga bagian',
    'putih matang dan kuning telur setengah matang (setelah matang atau',
    'sesuai selera). Angkat dan sisihkan.',
    'Ulangi proses yang sama untuk telur puyuh.',
    'Penyajian Bibimbap:',
    'Siapkan 4 mangkuk besar, letakkan nasi putih matang di dasar masing-masing mangkuk.',
    'Atur sayuran (bayam, tauge, wortel, mentimun, jamur shiitake, dan kimchi) di',
    'atas nasi dengan rapi.',
    'Tambahkan daging sapi yang sudah dimasak di atas nasi dan sayuran.',
    'Letakkan satu telur ayam setengah matang di tengah setiap mangkuk.',
    'Tambahkan telur puyuh di sekitar telur ayam.',
    'Tambahkan telur ikan diatasnya.',
    'Sajikan dengan saus gochujang di sampingnya, atau langsung di atas bibimbap sesuai selera.',
 ],
  ),
  RecipeModel(
    name: "Grilled Chicken Salad + Homemade Sweet Onion Dressing",
    image: "assets/grilled_chicken_salad.jpeg",
    category: "Chicken",
    duration: "1 Hour",
    serving: "2 Seving", ingredients: [
      'Bahan:',
      '2 dada ayam tanpa kulit dan tulang',
      '1 sendok makan minyak zaitun',
      'Garam dan lada hitam secukupnya',
      '6 cangkir campuran sayuran hijau (misalnya, selada romaine,bayam,arugula',
      '1 cangkir tomat ceri, belah dua',
      '1 mentimun, iris tipis',
      '1/2 bawang merah, iris tipis',
      '1 alpukat, iris',
      '1/4 cangkir keju feta hancur (opsional)',
      '1/4 cangkir almond panggang atau kacang pinus (opsional)',
      'Dressing Bawang Manis:',
      '1/2 bawang manis (misalnya, Vidalia atau bawang bombay manis), cincang halus',
      '1/4 cangkir cuka sari apel',
      '2 sendok makan madu atau sirup maple',
      '1 sendok teh mustard Dijon',
      '1/2 cangkir minyak zaitun',
      'Garam dan lada hitam secukupnya',
  ], instructions: [
    'Siapkan Dressing Bawang Manis:',
    'Dalam blender atau food processor,campurkan bawang manis cincang,cuka sari apel,',
    'madu atau sirup maple, dan mustard Dijon.',
    'Belender hingga halus.',
    'Sambil blender berjalan, tuangkan minyak zaitun secara perlahan untuk mengemulsi dressing.',
    'Bumbui dengan garam dan lada hitam secukupnya.Blender lagi hingga semua bahan tercampur',
    'dengan baik.',
    'Cicipi dan sesuaikan rasa jika diperlukan.Pindahkan dressing ke dalam wadah dan simpan',
    'dalam kulkas sampai siap digunakan.',
    'Siapkan Ayam Panggang:',
    'Panaskan panggangan atau grill pan dengan api sedang-tinggi.',
    'Lumuri dada ayam dengan minyak zaitun, garam, dan lada hitam.',
    'Panggang ayam selama 5-7 menit per siss, atau hingga ayam matang sepenuhnya',
    'dan mencapai suhu internal 75 derajat C',
    'Angkat ayam dari panggangan dan biarkan istirahar selama beberapa menit sebelum',
    'diiris tipis.',
    'Siapkan Salad:',
    'Dalam mangkuk besar, campurkan sayuran hijau,tomat ceri,mentimun,dan bawang merah.',
    'Atur irisan alpukat diatas sayuran.',
    'Tambahkan irisan ayam panggang di atas salad.',
    'Taburi dengan keju feta hancur dan almond panggang atau kacang pinus jika menggunakan.',
    'Penyajian:',
    'Sajikan salad dengan dressing bawang manis buatan sendiri yang telah disiapkan.',
    'Aduk salad dengan dressing sebelum disajikan atau biarkan setiap orang menambahkan',
    'dressing sesuai selera mereka.',
  ],
  ),
];

